version: '3.8'
services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092  # Kafka 연결 설정
    networks:
      - notification-network

  mysql:
    image: mysql:8.0
    container_name: mysql-notification
    restart: always
    environment:
      MYSQL_DATABASE: notification_db
      MYSQL_ROOT_PASSWORD: 5131
    ports:
      - "3306:3306"
    networks:
      - notification-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - notification-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge
