global:
  scrape_interval: 5s  # 5초마다 메트릭 수집
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8081']

  - job_name: 'newsfeed-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['newsfeed-service:8082']

  - job_name: 'chat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-service:8083']

  - job_name: 'search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8084']
