version: '3.8'

networks:
  msa-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "5131"
      MYSQL_USER: "sjin"
      MYSQL_PASSWORD: "5131"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    networks:
      - msa-network
    volumes:
      - ./init-scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
      - ./init-scripts/mock-data.sql:/docker-entrypoint-initdb.d/mock-data.sql

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - msa-network
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    networks:
      - msa-network
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
